Month9/step1
simplex83/React-Burger pull request #7
Opened 2023-02-16 12:02 UTC by simplex83

2023-02-16 13:24 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Просьба, пожалуйста перенаправьте ветку PR, на ветку предыдущего задания, а не на `main`. Чтобы было видно, какие файлы изменились за этот период.**

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/s_fHTlJsDMpeCQ>;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

### **Сделает код лучше:**

- Когда неавторизованный пользователь заходит на страницу `/profile`, поле успешного логина, перекидывать его обратно на ту же страницу, а не на главную.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-16 13:24 UTC, ArslanDev666 commented on src/services/actions/authorization.jsx
> +        console.log(res);
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/services/actions/authorization.jsx
> +        console.log(res);
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/services/actions/authorization.jsx
> +          console.log(res.message);
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/utils/cookies.jsx
> +    console.log(document.cookie);
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/services/actions/order-details.jsx
> +    console.log();
**Надо исправить:**

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/index.jsx
> +);
**Можно лучше:**

Лучше создать файлик index.js в папке services, и оттуда экспортировать эти данные.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.jsx
> +      <form className={styles.form} onSubmit={handleSubmitForgot}>
**Вы молодец:**

Вы правильно повесели обработчик событий на форму)) многие по ошибке вешают обработчик на событие `onClick` кнопки.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/utils/const.jsx
> +export const baseUrl = `https://norma.nomoreparties.space/api`
**Надо исправить:**

Константы принято записывать в стиле UPPER_CASE.

2023-02-16 13:24 UTC, ArslanDev666 commented on src/services/actions/authorization.jsx
> +        }
**Можно лучше:**

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      setCookie("accessToken", refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-02-17 13:04 UTC, simplex83 commented on src/services/actions/authorization.jsx
> +        console.log(res);
удалил

2023-02-17 13:05 UTC, simplex83 commented on src/services/actions/authorization.jsx
> +        console.log(res);
+

2023-02-17 13:05 UTC, simplex83 commented on src/services/actions/authorization.jsx
> +          console.log(res.message);
+

2023-02-17 13:07 UTC, simplex83 commented on src/utils/cookies.jsx
> +    console.log(document.cookie);
+

2023-02-17 13:07 UTC, simplex83 commented on src/services/actions/order-details.jsx
> +    console.log();
+

2023-02-17 13:11 UTC, simplex83 commented on src/utils/const.jsx
> +export const baseUrl = `https://norma.nomoreparties.space/api`
исправил

2023-02-17 19:17 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-27 13:22 UTC, merged